In [2]:
import torch

In [3]:
x = torch.arange(4.0)

In [3]:
x

tensor([0., 1., 2., 3.])

In [4]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [5]:
x.grad

In [12]:
y =2 * torch.dot(x,x)

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [16]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [15]:
x.grad == 4 * x

tensor([True, True, True, True])

In [17]:
x.grad

tensor([0., 0., 0., 0.])

In [18]:
y = x.sum()

In [19]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [21]:
y.backward()

In [22]:
x.grad

tensor([1., 1., 1., 1.])

In [23]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [7]:
y = x * x

In [25]:
y.backward(torch.ones(len(x)))

In [26]:
x.grad

tensor([0., 2., 4., 6.])

In [27]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [28]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [29]:
y = x * x

In [30]:
u = y.detach()

In [31]:
z = u * x

In [32]:
z.sum().backward()

In [33]:
x.grad == u

tensor([True, True, True, True])

In [34]:
x.grad

tensor([0., 1., 4., 9.])

In [35]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [36]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [37]:
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [14]:
a = torch.Tensor([[1,2], [3,4]])
b = torch.Tensor([[1,2,3,4], [1,2,3,4]])

In [17]:
torch.mul(a,b)

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1