In [2]:
import os

In [5]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [6]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [7]:
inputs,outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())

In [8]:
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [9]:
inputs = pd.get_dummies(inputs, dummy_na=True)

In [11]:
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [14]:
import torch
X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [15]:
x = torch.tensor([3.0])

In [16]:
y = torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [17]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [18]:
len(x)

4

In [19]:
x.shape

torch.Size([4])

In [20]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [21]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [22]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [24]:
X = torch.arange(24).reshape(4,6)

In [25]:
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [26]:
X * 2

tensor([[ 0,  2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32, 34],
        [36, 38, 40, 42, 44, 46]])

In [27]:
X.sum()

tensor(276)

In [28]:
X_sum_axis0 = X.sum(axis=0)
X_sum_axis0,X_sum_axis0.shape

(tensor([36, 40, 44, 48, 52, 56]), torch.Size([6]))

In [30]:
X_sum_axis1 = X.sum(axis=1)
X_sum_axis1,X_sum_axis0.shape

(tensor([ 15,  51,  87, 123]), torch.Size([4]))

In [31]:
sum_X = X.sum(axis=1,keepdims=True)
sum_X

tensor([[ 15],
        [ 51],
        [ 87],
        [123]])

In [32]:
X.cumsum(axis=0)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  8, 10, 12, 14, 16],
        [18, 21, 24, 27, 30, 33],
        [36, 40, 44, 48, 52, 56]])

In [33]:
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [34]:
X.cumsum(axis=0)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  8, 10, 12, 14, 16],
        [18, 21, 24, 27, 30, 33],
        [36, 40, 44, 48, 52, 56]])

In [35]:
X.shape

torch.Size([4, 6])

In [43]:
Y = torch.ones(6,2, dtype = torch.float32)

In [44]:
Y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [45]:
torch.dot(X,Y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [46]:
Y.shape



torch.Size([6, 2])

In [66]:
x,y = torch.ones(4,dtype = torch.float32),torch.tensor([1,2,3,4],dtype = torch.float32)
x,y

(tensor([1., 1., 1., 1.]), tensor([1., 2., 3., 4.]))

In [62]:
x + y

tensor([2., 3., 4., 5.])

In [63]:
x * y

tensor([1., 2., 3., 4.])

In [64]:
torch.sum(x*y)

tensor(10.)

In [67]:
torch.dot(x,y)

tensor(10.)

In [68]:
X

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [74]:
B = torch.ones(6,2,dtype = torch.long)

In [70]:
B

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [75]:
torch.mm(X,B)

tensor([[ 15,  15],
        [ 51,  51],
        [ 87,  87],
        [123, 123]])

In [76]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [77]:
torch.abs(u).sum()

tensor(7.)

In [1]:
import pandas as pd

In [2]:
%config Completer.use_jedi = False

In [ ]:
pd.